---
  extends: openstack/es2015
  parser: babel-eslint
  plugins:
    - react
  parserOptions:
    ecmaFeatures:
      jsx: true
  env:
    node: true
  rules:
    # extra/overriden values
    array-bracket-spacing: 2
    comma-spacing: 2
    curly: [2, multi-line, consistent]
    dot-location: [2, property]
    key-spacing: 2
    keyword-spacing: 2
    no-array-constructor: 2
    no-empty: [2, {allowEmptyCatch: true}]
    no-extra-parens: 0
    no-lonely-if: 2
    no-new-object: 2
    no-spaced-func: 2
    no-undef: 2
    no-unexpected-multiline: 2
    object-curly-spacing: 2
    operator-linebreak: [2, after, {overrides: {'?': ignore, ':': ignore}}]
    padded-blocks: [2, never]
    quotes: [2, single, avoid-escape]
    space-before-function-paren: [2, never]
    yoda: 2

    # node.js
    no-process-env: 0
    no-sync: 0

    # ES6
    computed-property-spacing: 2
    object-shorthand: [2, methods]

    # JSX
    jsx-quotes: [2, prefer-single]
    react/jsx-boolean-value: [2, never]
    react/jsx-closing-bracket-location: [2, {nonEmpty: false, selfClosing: line-aligned}]
    react/jsx-curly-spacing: 2
    react/jsx-equals-spacing: 2
    react/jsx-indent: [2, 2]
    react/jsx-indent-props: [2, 2]
    react/jsx-key: 2
    react/jsx-no-duplicate-props: 2
    react/jsx-no-literals: 2
    react/jsx-no-undef: 2
    react/jsx-pascal-case: 2
    react/jsx-space-before-closing: 2
    react/jsx-uses-react: 2
    react/jsx-uses-vars: 2
    react/no-deprecated: 2
    react/no-unknown-property: 2
    react/prefer-es6-class: 2
    react/react-in-jsx-scope: 2
    react/require-render-return: 2
    react/self-closing-comp: 2
